"""empty message

Revision ID: e7958d542ca5
Revises: 3a3bd3eac5c2
Create Date: 2020-04-24 10:19:09.882968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7958d542ca5'
down_revision = '3a3bd3eac5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=18), nullable=True),
    sa.Column('port', sa.String(length=10), nullable=True),
    sa.Column('net_type', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=12), nullable=True),
    sa.Column('anonymity', sa.String(length=10), nullable=True),
    sa.Column('speed', sa.String(length=10), nullable=True),
    sa.Column('connect_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxy')
    # ### end Alembic commands ###
