version: "3"
services: 
    crawler-web:
        image: crawler_web:latest
        container_name: crawlerWeb
        depends_on:
          - mysql
          - redis
        volumes:
            - ./crawler_web/logs:/crawler_web/logs
            - ./default:/etc/nginx/sites-available/default
        ports:
            - 8088:80

#    redis:
#        image: redis
#        container_name: redis
#        # command: --appendonly yes
#        command: redis-server --requirepass 123456
#        restart: always
#        volumes:
#            - ../data/redis/db:/data
#        ports:
#            - 63791:6379
#
#    mysql:
#        image: mysql
#        container_name: mysql
#        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
#        # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0 --default-authentication-plugin=mysql_native_password --skip-mysqlx
#        environment:
#            - MYSQL_ROOT_PASSWORD=shang.666
#            - MYSQL_USER=root
#            - MYSQL_PASSWORD=shang.666
#        restart: always
#        volumes:
#            - ../data/mysql/db:/var/lib/mysql
#            - ../data/mysql/conf/my.cnf:/etc/my.cnf
#            - ../data/mysql/init:/docker-entrypoint-initdb.d/
#        ports:
#            - 33061:3306
#
#    rabbitmq:
#        image: rabbitmq
#        container_name: rabbitmq
#        environment:
#            - RABBITMQ_DEFAULT_USER=admin   # 用户名
#            - RABBITMQ_DEFAULT_PASS=admin   # 密码
#            #            - RABBITMQ_DEFAULT_VHOST=my_vhost
#        restart: always
#        volumes:
#            - ../data/rabitmq:/var/lib/rabbitmq
#        ports:
#            - 5672:5672 #集群内部访问的端口
#            - 15672:15672 #外部访问的端口
#
### 集群部署时使用
##    rabbitmq1:
##        image: rabbitmq
##        container_name: rabbitmq1
##        environment:
##            - CLUSTERED=true
##            - CLUSTER_WITH=rabbit1
##            - RAM_NODE=true
##        restart: always
##        volumes:
##            - ./data/mysql/db:/var/lib/mysql
##            - ./data/mysql/conf/my.cnf:/etc/my.cnf
##            - ./data/mysql/init:/docker-entrypoint-initdb.d/
##        ports:
##            - 5673:5672 #集群内部访问的端口
##            - 15672:15672 #外部访问的端口
##        links:
##            - rabbitmq
