"""empty message

Revision ID: c7c0cbefcbaa
Revises: 
Create Date: 2020-09-07 19:37:21.795103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c0cbefcbaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dytt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('classify', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('size', sa.String(length=8), nullable=True),
    sa.Column('introduction', sa.String(length=32), nullable=True),
    sa.Column('magnet', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=18), nullable=True),
    sa.Column('port', sa.String(length=10), nullable=True),
    sa.Column('net_type', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=12), nullable=True),
    sa.Column('anonymity', sa.String(length=10), nullable=True),
    sa.Column('speed', sa.String(length=10), nullable=True),
    sa.Column('connect_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=18), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('proxy')
    op.drop_table('dytt')
    # ### end Alembic commands ###
